/**
 * Database Types
 *
 * This file will be auto-generated by running:
 * npm run db:generate
 *
 * It contains TypeScript types for all your Supabase tables.
 *
 * After you set up your database schema and run migrations,
 * run the generate command to populate this file.
 */

// Placeholder types until schema is deployed
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be auto-generated here
    }
    Views: {
      // Views will be auto-generated here
    }
    Functions: {
      // Functions will be auto-generated here
    }
    Enums: {
      // Enums will be auto-generated here
    }
  }
}
